fixes test failure for AuthenticationTokenSecretManager
AuthenticationTokenSecretManager was calling System.currentTimeMillis()
twice causing the following test sporadic failure. Modified to only get
time once to avoid test failure.

```
[ERROR] org.apache.accumulo.server.security.delegation.AuthenticationTokenSecretManagerTest.testGenerateToken -- Time elapsed: 0.011 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1729199138567> but was: <1729199138568>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:632)
	at org.apache.accumulo.server.security.delegation.AuthenticationTokenSecretManagerTest.testGenerateToken(AuthenticationTokenSecretManagerTest.java:174)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```